import type { Asset, Comment, ExchangeRates, Post, Thesis } from "./types"

export const asset: Asset = {
  ticker: "NVDA",
  name: "NVIDIA Corp.",
  sector: "Semiconductores",
  currency: "USD",
  price: 185.2,
}

export const exchangeRates: ExchangeRates = {
  EUR: 0.92,
  GBP: 0.79,
  JPY: 147,
}

export const posts: Post[] = [
  {
    id: "p1",
    type: "POST",
    assetTicker: "NVDA",
    author: { handle: "martincode" },
    createdAt: "2026-09-10T09:00:00.000Z", // hace 3h
    upvotes: 128,
    downvotes: 12,
    commentCount: 4,
    body: "La nueva arquitectura Blackwell ya está copando los pedidos de los hyperscalers. Microsoft y Meta confirmaron ampliación de pedidos para el próximo trimestre. El cuello de botella sigue siendo capacidad de empaquetado en TSMC, no demanda.",
    userVote: null,
  },
  {
    id: "p2",
    type: "POST",
    assetTicker: "NVDA",
    author: { handle: "valeinversora" },
    createdAt: "2026-09-09T12:00:00.000Z", // hace 1 día
    upvotes: 74,
    downvotes: 31,
    commentCount: 7,
    body: "A 35x ganancias forward, el mercado ya está descontando varios años de crecimiento a tasas actuales. No digo que sea mala empresa, digo que el precio no deja mucho margen de error.",
    userVote: null,
  },
  {
    id: "p3",
    type: "POST",
    assetTicker: "NVDA",
    author: { handle: "shortandlong" },
    createdAt: "2026-09-08T12:00:00.000Z", // hace 2 días
    upvotes: 45,
    downvotes: 9,
    commentCount: 3,
    body: "El CEO vendió otro tramo de acciones esta semana. Ya van varios insiders liquidando posiciones en los últimos meses. ¿Alguien más lo está siguiendo?",
    userVote: null,
  },
]

export const theses: Thesis[] = [
  {
    id: "t1",
    type: "THESIS",
    assetTicker: "NVDA",
    author: { handle: "deep.value" },
    createdAt: "2026-09-06T12:00:00.000Z", // hace 4 días
    upvotes: 312,
    downvotes: 28,
    commentCount: 12,
    claim: "$NVDA superará los $250 antes del 15 de marzo de 2027",
    direction: "ABOVE",
    targetPrice: 250,
    deadline: "2027-03-15T23:59:59.000Z",
    conviction: "HIGH",
    reasoning:
      "El capex de los hyperscalers en infraestructura de IA sigue acelerando de cara a 2027, y NVIDIA mantiene share dominante en entrenamiento e inferencia. El ecosistema CUDA eleva el costo de cambiar de proveedor y sostiene el múltiplo actual.",
    status: "OPEN",
    outcome: null,
    resolvedAt: null,
    resolutionPrice: null,
    userVote: null,
  },
  {
    id: "t2",
    type: "THESIS",
    assetTicker: "NVDA",
    author: { handle: "shortandlong" },
    createdAt: "2026-06-10T12:00:00.000Z", // hace 3 meses
    upvotes: 96,
    downvotes: 145,
    commentCount: 9,
    claim: "$NVDA no superará los $200 antes del 30 de junio de 2026",
    direction: "BELOW",
    targetPrice: 200,
    deadline: "2026-06-30T23:59:59.000Z",
    conviction: "MEDIUM",
    reasoning:
      "Los chips propios de los hyperscalers vienen reemplazando una porción creciente de su demanda interna, y AMD cierra la brecha de performance más rápido de lo que descuenta el mercado. Es una tesis de compresión de márgenes, no de colapso.",
    status: "CLOSED",
    outcome: "CORRECT",
    resolvedAt: "2026-06-30T21:00:00.000Z",
    resolutionPrice: 178.4,
    userVote: null,
  },
]

export const comments: Comment[] = [
  // --- P1 (seed 2 + 2 extra = 4) ---
  {
    id: "c-p1-1",
    contentId: "p1",
    author: { handle: "florv" },
    body: "¿Alguna fuente de esos números o es lo que se comenta en el sector?",
    createdAt: "2026-09-10T09:30:00.000Z",
    upvotes: 8,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-p1-2",
    contentId: "p1",
    author: { handle: "renelong" },
    body: "El cuello de botella en CoWoS viene desde 2023, no es nuevo.",
    createdAt: "2026-09-10T10:00:00.000Z",
    upvotes: 14,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-p1-3",
    contentId: "p1",
    author: { handle: "deep.value" },
    body: "Si el cuello de botella es empaquetado y no demanda, la lectura para 2027 es distinta a la que hace el mercado hoy.",
    createdAt: "2026-09-10T10:30:00.000Z",
    upvotes: 6,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-p1-4",
    contentId: "p1",
    author: { handle: "valeinversora" },
    body: "Coincido, pero eso también significa que el consenso de crecimiento ya está poniendo el foco donde corresponde, así que no debería sorprender a nadie en el precio.",
    createdAt: "2026-09-10T11:00:00.000Z",
    upvotes: 3,
    downvotes: 2,
    userVote: null,
  },

  // --- P2 (seed 2 + 5 extra = 7) ---
  {
    id: "c-p2-1",
    contentId: "p2",
    author: { handle: "deep.value" },
    body: "Depende de qué crecimiento asumís para datacenter en 2026. Ahí está la discusión.",
    createdAt: "2026-09-09T14:00:00.000Z",
    upvotes: 11,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-p2-2",
    contentId: "p2",
    author: { handle: "martincode" },
    body: "35x forward con revenue creciendo 80% interanual no me parece caro.",
    createdAt: "2026-09-09T15:00:00.000Z",
    upvotes: 19,
    downvotes: 4,
    userVote: null,
  },
  {
    id: "c-p2-3",
    contentId: "p2",
    author: { handle: "florv" },
    body: "El múltiplo forward asume que el 80% se sostiene, y ahí es donde cada uno pone su propio número.",
    createdAt: "2026-09-09T16:00:00.000Z",
    upvotes: 9,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-p2-4",
    contentId: "p2",
    author: { handle: "shortandlong" },
    body: "Coincido con vale: cuando todo el mundo asume que el crecimiento sigue igual es cuando conviene ser más conservador.",
    createdAt: "2026-09-09T17:00:00.000Z",
    upvotes: 7,
    downvotes: 5,
    userVote: null,
  },
  {
    id: "c-p2-5",
    contentId: "p2",
    author: { handle: "renelong" },
    body: "35x en semis históricamente comprimió rápido apenas el crecimiento se desacelera, no hace falta que colapse la demanda.",
    createdAt: "2026-09-09T18:00:00.000Z",
    upvotes: 12,
    downvotes: 2,
    userVote: null,
  },
  {
    id: "c-p2-6",
    contentId: "p2",
    author: { handle: "quantcarla" },
    body: "El punto de vale no es que NVDA sea mala, es que el margen de error para sorpresas negativas es chico a este múltiplo.",
    createdAt: "2026-09-10T08:00:00.000Z",
    upvotes: 5,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-p2-7",
    contentId: "p2",
    author: { handle: "martincode" },
    body: "Ahí sí coincido: el riesgo no es la tesis de fondo sino la reacción del precio ante cualquier bache.",
    createdAt: "2026-09-10T09:00:00.000Z",
    upvotes: 4,
    downvotes: 0,
    userVote: null,
  },

  // --- P3 (seed 2 + 1 extra = 3) ---
  {
    id: "c-p3-1",
    contentId: "p3",
    author: { handle: "florv" },
    body: "La mayoría son ventas programadas (10b5-1), no es necesariamente una señal.",
    createdAt: "2026-09-08T13:00:00.000Z",
    upvotes: 10,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-p3-2",
    contentId: "p3",
    author: { handle: "valeinversora" },
    body: "Programadas o no, el volumen viene subiendo trimestre a trimestre.",
    createdAt: "2026-09-08T15:00:00.000Z",
    upvotes: 6,
    downvotes: 2,
    userVote: null,
  },
  {
    id: "c-p3-3",
    contentId: "p3",
    author: { handle: "macrofede" },
    body: "El volumen sube porque el paquete de compensación también creció; hay que mirarlo en % del holding, no en monto absoluto.",
    createdAt: "2026-09-08T17:00:00.000Z",
    upvotes: 8,
    downvotes: 0,
    userVote: null,
  },

  // --- T1 (seed 2 + 10 extra = 12) ---
  {
    id: "c-t1-1",
    contentId: "t1",
    author: { handle: "shortandlong" },
    body: "El argumento de CUDA es el más sólido acá, más que el crecimiento de corto plazo.",
    createdAt: "2026-09-06T14:00:00.000Z",
    upvotes: 41,
    downvotes: 2,
    userVote: null,
  },
  {
    id: "c-t1-2",
    contentId: "t1",
    author: { handle: "renelong" },
    body: "¿Qué pasa con esta tesis si un hyperscaler anuncia chip propio a gran escala?",
    createdAt: "2026-09-06T17:00:00.000Z",
    upvotes: 28,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-t1-3",
    contentId: "t1",
    author: { handle: "deep.value" },
    body: "Ya hay varios anunciados (Trainium, TPU, MTIA) y ninguno le sacó share relevante a NVIDIA todavía; el ecosistema de software pesa más que el silicio.",
    createdAt: "2026-09-06T18:00:00.000Z",
    upvotes: 33,
    downvotes: 3,
    userVote: null,
  },
  {
    id: "c-t1-4",
    contentId: "t1",
    author: { handle: "martincode" },
    body: "El riesgo que le veo no es el chip propio sino el ritmo de capex si hay una corrección macro fuerte.",
    createdAt: "2026-09-07T12:00:00.000Z",
    upvotes: 19,
    downvotes: 4,
    userVote: null,
  },
  {
    id: "c-t1-5",
    contentId: "t1",
    author: { handle: "valeinversora" },
    body: "186 días da mucho margen, pero también mucho tiempo para que cambie el consenso sobre 2027.",
    createdAt: "2026-09-07T15:00:00.000Z",
    upvotes: 12,
    downvotes: 6,
    userVote: null,
  },
  {
    id: "c-t1-6",
    contentId: "t1",
    author: { handle: "florv" },
    body: "¿La convicción alta contempla algún escenario de corrección de múltiplo aunque el negocio siga creciendo?",
    createdAt: "2026-09-07T18:00:00.000Z",
    upvotes: 9,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-t1-7",
    contentId: "t1",
    author: { handle: "quantcarla" },
    body: "Con el consenso actual de EPS, $250 implica un múltiplo razonable si sostiene el crecimiento de datacenter, no es una apuesta extrema.",
    createdAt: "2026-09-08T12:00:00.000Z",
    upvotes: 22,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-t1-8",
    contentId: "t1",
    author: { handle: "shortandlong" },
    body: "Ojo que 'razonable' hoy depende de que ningún hyperscaler recorte guidance de capex; ahí es donde miraría primero.",
    createdAt: "2026-09-08T16:00:00.000Z",
    upvotes: 17,
    downvotes: 3,
    userVote: null,
  },
  {
    id: "c-t1-9",
    contentId: "t1",
    author: { handle: "renelong" },
    body: "CUDA es una barrera real, pero también es la parte que más presión regulatoria/antitrust puede atraer en 2026-2027.",
    createdAt: "2026-09-08T20:00:00.000Z",
    upvotes: 8,
    downvotes: 2,
    userVote: null,
  },
  {
    id: "c-t1-10",
    contentId: "t1",
    author: { handle: "macrofede" },
    body: "Coincido con deep.value: el software lock-in es la parte de la tesis que menos se discute y probablemente la más importante.",
    createdAt: "2026-09-09T12:00:00.000Z",
    upvotes: 15,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-t1-11",
    contentId: "t1",
    author: { handle: "martincode" },
    body: "Convicción alta me parece bien puesta: el riesgo principal es de timing, no de dirección.",
    createdAt: "2026-09-09T17:00:00.000Z",
    upvotes: 11,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-t1-12",
    contentId: "t1",
    author: { handle: "deep.value" },
    body: "Voy a actualizar si sale algo concreto de capex para 2027 en los próximos reportes.",
    createdAt: "2026-09-09T20:00:00.000Z",
    upvotes: 14,
    downvotes: 0,
    userVote: null,
  },

  // --- T2 (seed 2 + 7 extra = 9; mezcla de comentarios previos y posteriores al cierre 2026-06-30) ---
  {
    id: "c-t2-1",
    contentId: "t2",
    author: { handle: "deep.value" },
    body: "El custom silicon lleva años 'por llegar' y la brecha de software sigue siendo enorme.",
    createdAt: "2026-06-11T12:00:00.000Z",
    upvotes: 52,
    downvotes: 8,
    userVote: null,
  },
  {
    id: "c-t2-2",
    contentId: "t2",
    author: { handle: "martincode" },
    body: "Coincido en la dirección, discrepo en el timing: pensé que esto se jugaba en 2027-2028.",
    createdAt: "2026-06-13T12:00:00.000Z",
    upvotes: 38,
    downvotes: 5,
    userVote: null,
  },
  {
    id: "c-t2-3",
    contentId: "t2",
    author: { handle: "renelong" },
    body: "El margen de compresión ya se empezó a ver en el gross margin del último trimestre; la tesis tiene más sustento del que el score refleja.",
    createdAt: "2026-06-15T12:00:00.000Z",
    upvotes: 29,
    downvotes: 6,
    userVote: null,
  },
  {
    id: "c-t2-4",
    contentId: "t2",
    author: { handle: "valeinversora" },
    body: "145 en contra me parece que subestima cuánto está creciendo todavía la demanda interna de los hyperscalers.",
    createdAt: "2026-06-20T12:00:00.000Z",
    upvotes: 8,
    downvotes: 22,
    userVote: null,
  },
  {
    id: "c-t2-5",
    contentId: "t2",
    author: { handle: "quantcarla" },
    body: "Con pocos días para el deadline, $200 sigue lejos salvo un rally muy fuerte de acá al 30/6.",
    createdAt: "2026-06-25T12:00:00.000Z",
    upvotes: 14,
    downvotes: 3,
    userVote: null,
  },
  {
    id: "c-t2-6",
    contentId: "t2",
    author: { handle: "martincode" },
    body: "Cerró en $178.40: la tesis acertó y encima contra el consenso de la votación. Hay que sacarse el sombrero acá.",
    createdAt: "2026-07-01T12:00:00.000Z",
    upvotes: 61,
    downvotes: 2,
    userVote: null,
  },
  {
    id: "c-t2-7",
    contentId: "t2",
    author: { handle: "deep.value" },
    body: "Reconozco que voté en contra y el argumento de compresión de márgenes por custom silicon + AMD terminó siendo más determinante de lo que pensé.",
    createdAt: "2026-07-02T12:00:00.000Z",
    upvotes: 47,
    downvotes: 1,
    userVote: null,
  },
  {
    id: "c-t2-8",
    contentId: "t2",
    author: { handle: "florv" },
    body: "Lo interesante es que el precio no colapsó, se comprimió gradual como decía la tesis; no fue un evento de pánico.",
    createdAt: "2026-07-05T12:00:00.000Z",
    upvotes: 20,
    downvotes: 0,
    userVote: null,
  },
  {
    id: "c-t2-9",
    contentId: "t2",
    author: { handle: "macrofede" },
    body: "Buen recordatorio de que el score de la comunidad mide expectativa, no certeza: 145 en contra y terminó correcta.",
    createdAt: "2026-07-10T12:00:00.000Z",
    upvotes: 25,
    downvotes: 3,
    userVote: null,
  },
]
